name: Code Coverage

on:
  push:
    branches:
    - main
    - actions
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Concurrency
      run: echo NPROC="nproc" >> $GITHUB_ENV

    - name: Set Up Dependencies
      run: |
        sudo apt install -y cmake pkg-config lcov g++-10

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-10 -DCOVERAGE=ON

    - name: Build All
      working-directory: ${{runner.workspace}}/build
      run: make -j $($NPROC)

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j $($NPROC)

    - name: Generate Code Coverage
      working-directory: ${{runner.workspace}}/HermesBDD
      run: |
        lcov --directory ${{runner.workspace}}/build --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"